import { createElement } from 'lwc';
import Sap_FinsysDashboardPdfGenerator from 'c/sap_FinsysDashboardPdfGenerator';

describe('c-sap-finsys-dashboard-pdf-generator', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-sap-finsys-dashboard-pdf-generator', {
            is: Sap_FinsysDashboardPdfGenerator
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});